-- vim.api.nvim_command('syntax on')
-- vim.api.nvim_command('colorscheme space-vim-dark')
-- set termguicolors
-- hi Normal     ctermbg=NONE guibg=NONE
-- hi LineNr     ctermbg=NONE guibg=NONE
-- hi SignColumn ctermbg=NONE guibg=NONE
-- hi CursorLineNr ctermbg=NONE guibg=NONE
-- hi LineNr guifg=white guibg=NONE ctermfg=white ctermbg=NONE
-- hi Comment cterm=italic gui=italic
