-- local status_ok, jdtls = pcall(require, "jdtls")
--
-- if not status_ok then
--   print('jdtls not work')
--   return
-- end
--
-- -- TODO https://github.com/mfussenegger/nvim-jdtls/discussions/187
-- -- TODO https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/1746
-- local config = {
--   cmd = { vim.fn.stdpath("data") .. '/mason/bin/jdtls' },
--   root_dir = vim.fs.dirname(vim.fs.find({ '.gradlew', '.git', 'mvnw' }, { upward = true })[1]),
-- }
--
--
-- jdtls.start_or_attach(config)
